stages:
- build

frontend:
  stage: build
  # https://hub.docker.com/_/node/
  image: node:alpine
  before_script:
    - npm set fetch-retries 10
  script:
    - npm install
    - npm run build:aot:prod
