stages:
- build

frontend:
  stage: build
  # https://hub.docker.com/r/iron/node/
  image: iron/node
  cache:
    untracked: true
    key: "frontend_npm"
    paths:
    - .npm/
    - node_modules/
  before_script:
    - npm set cache .npm
    - npm set fetch-retries 10
    - npm cache verify
  script:
    - npm install
    - npm run build:aot:prod
  artifacts:
    paths:
    - .npm/
    - node_modules/
    expire_in: 1 week
    when: always
