stages:
- build_node_modules
- test
- build

node_modules:
  stage: build_node_modules
  # https://hub.docker.com/_/node/
  image: node:7-alpine
  cache:
    key: "frontend_npm"
    paths:
    - .npm/
  before_script:
    - npm set cache .npm
    - npm set fetch-retries 10
  script:
    - npm install
  artifacts:
    paths:
    - node_modules/

lint:
  stage: test
  dependencies:
    - node_modules
  # https://hub.docker.com/_/node/
  image: node:7-alpine
  script:
    - npm run lint

npm:
  stage: build
  dependencies:
    - node_modules
  # https://hub.docker.com/_/node/
  image: node:7-alpine
  script:
    - npm run build:aot:prod
  artifacts:
    paths:
    - dist/
