stages:
- build

frontend:
  stage: build
  # https://hub.docker.com/_/node/
  image: node:alpine
  cache:
    key: "frontend_npm"
    paths:
    - .npm/
  before_script:
    - npm set cache .npm
    - npm set fetch-retries 5
    - npm cache verify
  script:
    - npm install
    - npm run build:aot:prod
