stages:
- build_node_modules
- build
- build_image
- test_image

variables:
  IMAGE_NAME_PRO: $CI_REGISTRY/jukebox/frontend/pro:$CI_COMMIT_REF_SLUG

node_modules:
  stage: build_node_modules
  # https://hub.docker.com/_/node/
  image: node:7-alpine
  cache:
    key: "frontend_npm"
    paths:
    - .npm/
  before_script:
    - npm set cache .npm
    - npm set fetch-retries 10
  script:
    - npm install
  artifacts:
    paths:
    - node_modules/

npm:
  stage: build
  dependencies:
    - node_modules
  # https://hub.docker.com/_/node/
  image: node:7-alpine
  script:
    - npm run build:aot:prod
  artifacts:
    paths:
    - dist/

docker_image:
  stage: build_image
  dependencies:
    - npm
  script:
    - docker build --pull -t $IMAGE_NAME_PRO .

nginx_syntax:
  stage: test_image
  dependencies: []
  script:
    - docker run $IMAGE_NAME_PRO nginx -t
