stages:
- build

production:
  stage: build
  # https://hub.docker.com/_/node/
  image: node:7-alpine
  cache:
    key: "frontend_npm"
    paths:
    - .npm/
  before_script:
    - npm set cache .npm
    - npm set fetch-retries 10
  script:
    - npm install
    - npm run build:aot:prod
  artifacts:
    paths:
    - dist/
